version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: funcionarios_sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"  # Atenção: O SQL Server exige senha forte
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - funcionarios_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funcionarios_api
    restart: always
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=funcionariosdb;User Id=sa;Password=YourStrong!Passw0rd;
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - funcionarios_network

volumes:
  sqlserver_data:

networks:
  funcionarios_network:
    driver: bridge
