services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: funcionarios_sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - funcionarios_network

  api:
    build:
      context: ./Empresa.Funcionarios.Api
      dockerfile: Dockerfile
    container_name: funcionarios_api
    restart: always
    depends_on:
      - sqlserver
    # environment:
      # - ConnectionStrings__DefaultConnection=server=JULIOAVELL-PC;database=EmpresaFuncionarios;Trusted_Connection=True; TrustServerCertificate=True;
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - funcionarios_network

volumes:
  sqlserver_data:

networks:
  funcionarios_network:
    driver: bridge
