version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: funcionarios_postgres
    restart: always
    environment:
      POSTGRES_DB: funcionariosdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - funcionarios_network

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: funcionarios_api
    restart: always
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=funcionariosdb;Username=admin;Password=admin
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - funcionarios_network

volumes:
  postgres_data:

networks:
  funcionarios_network:
    driver: bridge
