//// <auto-generated />
//using System;
//using System.Collections.Generic;
//using Empresa.Funcionarios.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

//#nullable disable

//namespace Empresa.Funcionarios.Data.Migrations
//{
//    [DbContext(typeof(FuncionarioDbContext))]
//    partial class FuncionarioDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.13")
//                .HasAnnotation("Relational:MaxIdentifierLength", 63);

//            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

//            modelBuilder.Entity("Empresa.Funcionarios.Domain.Entities.Funcionario", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateTime>("DataNascimento")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<Guid?>("GestorId")
//                        .HasColumnType("uuid");

//                    b.Property<string>("Nome")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("NumeroDocumento")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("SenhaHash")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("Sobrenome")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<List<string>>("Telefones")
//                        .IsRequired()
//                        .HasColumnType("text[]");

//                    b.HasKey("Id");

//                    b.HasIndex("NumeroDocumento")
//                        .IsUnique();

//                    b.ToTable("Funcionarios");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
